#!/bin/bash

echo "🚀 Setting Up Full Google OAuth with All APIs"
echo "============================================="
echo ""

PROJECT_ID="thistracker"
USER_EMAIL="fabionbalielo@gmail.com"

echo "✅ Current Status:"
echo "   - Basic OAuth: Working ✅"
echo "   - Google APIs: Enabled ✅"
echo "   - Project: $PROJECT_ID"
echo "   - Account: $USER_EMAIL"
echo ""

echo "🔧 Next Steps: Configure OAuth Consent Screen"
echo "============================================="
echo ""
echo "Since basic OAuth works, we need to add the extended scopes"
echo "to the OAuth consent screen. Here are the exact steps:"
echo ""

echo "📋 Step 1: Access OAuth Consent Screen"
echo "====================================="
echo "Try these URLs in order:"
echo ""
echo "1. Primary: https://console.cloud.google.com/apis/credentials/consent?project=$PROJECT_ID"
echo "2. Alternative: https://console.cloud.google.com/apis/credentials?project=$PROJECT_ID"
echo "3. Dashboard: https://console.cloud.google.com/home/dashboard?project=$PROJECT_ID"
echo ""

echo "📋 Step 2: Configure OAuth Consent Screen"
echo "========================================"
echo "1. Click 'Edit App' or 'Configure Consent Screen'"
echo "2. Fill in required fields:"
echo "   - App name: ThisTracker"
echo "   - User support email: $USER_EMAIL"
echo "   - App domain: localhost"
echo "   - Developer contact: $USER_EMAIL"
echo "   - App description: Time tracking application with Google integration"
echo "3. Click 'Save and Continue'"
echo ""

echo "📋 Step 3: Add Scopes"
echo "===================="
echo "1. Go to 'Scopes' tab"
echo "2. Click 'Add or Remove Scopes'"
echo "3. Add these scopes:"
echo "   - https://www.googleapis.com/auth/calendar"
echo "   - https://www.googleapis.com/auth/drive"
echo "   - https://www.googleapis.com/auth/documents"
echo "   - https://www.googleapis.com/auth/spreadsheets"
echo "4. Click 'Update'"
echo "5. Click 'Save and Continue'"
echo ""

echo "📋 Step 4: Add Test Users"
echo "========================"
echo "1. Go to 'Test users' tab"
echo "2. Click '+ ADD USERS'"
echo "3. Add: $USER_EMAIL"
echo "4. Click 'Save'"
echo ""

echo "📋 Step 5: Review and Publish"
echo "============================"
echo "1. Go to 'Summary' tab"
echo "2. Review all settings"
echo "3. Click 'Back to Dashboard'"
echo ""

echo "📋 Step 6: Test Full OAuth"
echo "========================="
echo "1. Wait 5-10 minutes for changes to propagate"
echo "2. Sign out of your app"
echo "3. Sign in again - you should see permission request for all APIs"
echo "4. Grant all permissions"
echo "5. Test the time tracker features"
echo ""

echo "🔧 Troubleshooting:"
echo "=================="
echo "If you still can't access the console:"
echo "1. Try incognito/private window"
echo "2. Try different browser"
echo "3. Clear browser cache"
echo "4. Try from mobile device"
echo ""

echo "🌐 Opening OAuth Consent Screen..."
open "https://console.cloud.google.com/apis/credentials/consent?project=$PROJECT_ID"

echo ""
echo "📝 Note: The full OAuth configuration is now restored."
echo "You just need to update the consent screen to allow the extended scopes."
